carrinho/urls.py
from django.urls import path
from . import views

app_name = "carrinho"

urlpatterns = [
    path('', views.detalhes_carrinho, name='detalhes_carrinho'),
    path('adicionar/<int:id_produto>/', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('remover/<int:id_produto>/', views.remover_do_carrinho, name='remover_do_carrinho')
]

core/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name='core'

urlpatterns = [
    path('', views.index, name='index'), 
    path('produtos/', views.listar_produtos, name='listar_produtos'),
    path('produtos/<str:slug_categoria>/', views.listar_produtos, name='listar_produtos_por_categoria' ),
    path('produto/<str:slug_produto>/<int:id>/', views.detalhes_produtos, name='detalhes_produto')
]

lojaVirtual/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from core import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ajuda/', TemplateView.as_view(template_name='ajuda.html'), name='ajuda'),
    path('fale-conosco/', views.ViewFaleConosco.as_view(), name='fale_conosco'),
    path('carrinho/', include('carrinho.urls', namespace='carrinho')),
    path('pedidos/', include('pedidos.urls', namespace='pedidos')),
    path('', include('core.urls', namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedidos/urls.py
from django.urls import path
from . import views

app_name = "pedidos"

urlpatterns = [
    path('criar/', views.criar_pedido, name="criar_pedido")
]

carrinho/models.py
from django.db import models

# Create your models here.

carrinho/forms.py
from django import forms

OPCOES_QUANTIDADE_PRODUTO = []

for i in range(1, 50):
    OPCOES_QUANTIDADE_PRODUTO.append((i, str(i)))

class FormAdicionarProdutoCarrinho(forms.Form):
    quantidade = forms.TypedChoiceField(
        choices=OPCOES_QUANTIDADE_PRODUTO, coerce=int)
    atualizar = forms.BooleanField(required=False, widget=forms.HiddenInput)

carrinho/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.views.decorators.http import require_POST
from core.models import Produto
from .carrinho import Carrinho
from .forms import FormAdicionarProdutoCarrinho 

# Create your views here.
@require_POST
def adicionar_ao_carrinho(request, id_produto):
    carrinho = Carrinho(request)
    produto = get_object_or_404(Produto, id=id_produto)
    form = FormAdicionarProdutoCarrinho(request.POST)

    if form.is_valid():
        dados = form.cleaned_data
        carrinho.adicionar(produto=produto,
        quantidade=dados['quantidade'],
        atualizar_quantidade=dados['atualizar'])
    
    return redirect('carrinho:detalhes_carrinho')

def remover_do_carrinho(request, id_produto):
    carrinho = Carrinho(request)
    produto = get_object_or_404(Produto, id=id_produto)
    carrinho.remover(produto)
    return redirect('carrinho:detalhes_carrinho')

def detalhes_carrinho(request):
    carrinho = Carrinho(request)
    list_produtos = []
    lista_produtos_filtrados = []
    for item in carrinho:
        item['formulario_adicionar_produto_ao_carrinho'] = FormAdicionarProdutoCarrinho(
            initial={'quantidade': item['quantidade'],
            'atualizar': True}
        )
        list_produtos.append(item)
    for item in list_produtos:
        if item not in lista_produtos_filtrados:
            lista_produtos_filtrados.append(item)
        
    return render(request, 'carrinho/detalhes.html', {'carrinho': lista_produtos_filtrados, 'valorTotal': carrinho})

templates/carrinho/detalhes.html
{%extends 'base.html' %}
{% load static %}
{% block titulo %}
    Seu Carrinho de compras
{% endblock %}

{% block conteudo %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
            <h2>Seu Carrinho de compra
                <span class="badge pull-right">
                    {% with total_de_itens=carrinho|length %}
                        {% if carrinho|length > 0 %}
                            Seu Pedidos:
                            <a href="
                                {% url "carrinho:detalhes_carrinho" %}"
                                style="color: #ffffff">
                                {{ total_de_itens }} item/itens,
                                {{ valorTotal.get_total_geral }}
                            </a>
                            {% else %}
                                Seu carrinho está vazio
                        {% endif %}
                    {% endwith %}
                </span>
            </h2>
                <table class="table table-striped table-hover">
                    <thead style="background-color: #5AC8FA">
                        <tr>
                            <th>imagem</th>
                            <th>Produto</th>
                            <th>Quantidade</th>
                            <th>Remover</th>
                            <th>Preço unitario</th>
                            <th>Subtotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in carrinho %}
                            
                            {% with produto=item.produto %}
                                <tr>
                                    <td>
                                        <img src="{% if produto.imagem %}
                                            {{produto.imagem.url}}
                                        {% else %}
                                        {% static
                                            'img/default.jpg'%}
                                        {% endif %}"
                                        alt="imagem de {{produto.nome}}"
                                        style="height: 100px; width: auto"/>
                                    </td>
                                    <td>{{produto.nome}}</td>
                                    <td>
                                        <form action="{% url "carrinho:adicionar_ao_carrinho" produto.id%}" method="POST">
                                            {%csrf_token %}
                                            {{item.formulario_adicionar_produto_ao_carrinho.quantidade}}
                                            {{item.formulario_adicionar_produto_ao_carrinho.atualizar}}
                                            <input type="submit" value="atualizar" class="btn btn-info">
                                        </form>
                                    </td>
                                    <td>
                                        <a href="{% url "carrinho:remover_do_carrinho" produto.id%}" class="btn btn-primary">
                                            Remover
                                        </a>
                                    </td>
                                    <td>R$ {{item.preco}}</td>
                                    <td>R$ {{item.subtotal}}</td>
                                </tr>
                            {%endwith%}
                        {%endfor%}
                        <tr style="background-color: #5AC8FA">
                            <td><b>Total</b></td>
                            <td colspan="4"></td>
                            <td colspan="num">
                                <b>R$ {{valorTotal.get_total_geral}}</b>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <p class="text-right">
                    <a href="{% url 'core:listar_produtos'%}" class="btn btn-primary button-light">
                        Comprar mais produtos
                    </a>
                    <a href="{% url 'pedidos:criar_pedido'%}" class="btn btn-secondary button">
                        Finalizar
                    </a>
                </p>
        </div>
    </div>
{% endblock %}