carrinho/urls.py
from django.urls import path
from . import views

app_name = "carrinho"

urlpatterns = [
    path('', views.detalhes_carrinho, name='detalhes_carrinho'),
    path('adicionar/<int:id_produto>/', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('remover/<int:id_produto>/', views.remover_do_carrinho, name='remover_do_carrinho')
]

core/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name='core'

urlpatterns = [
    path('', views.index, name='index'), 
    path('produtos/', views.listar_produtos, name='listar_produtos'),
    path('produtos/<str:slug_categoria>/', views.listar_produtos, name='listar_produtos_por_categoria' ),
    path('produto/<str:slug_produto>/<int:id>/', views.detalhes_produtos, name='detalhes_produto')
]

lojaVirtual/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from core import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ajuda/', TemplateView.as_view(template_name='ajuda.html'), name='ajuda'),
    path('fale-conosco/', views.ViewFaleConosco.as_view(), name='fale_conosco'),
    path('carrinho/', include('carrinho.urls', namespace='carrinho')),
    path('pedidos/', include('pedidos.urls', namespace='pedidos')),
    path('', include('core.urls', namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/barra_navegacao.html
<nav class="navbar bg-primary navbar-expand-lg fixed-top navbar-light text-white">
    <div class="container-fluid">
      <a class="navbar-brand text-white" href="#">Loja Virtual</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                  <a class="nav-link text-light" href="/">
                    Pagina Principal
                  </a>
              </li>
              <li class="nav-item">
                  <a class="nav-link text-light" href="/admin/core/categoria/">
                    Manutenção de categoria
                  </a>
              </li>
              <li class="nav-item">
                  <a class="nav-link text-light" href="/admin/core/produto/">
                    Manutenção de Produtos
                  </a>
              </li>
              <li class="nav-item">
                  <a class="nav-link text-light" href="/produtos/">
                    Comprar
                  </a>
              </li>
              <li class="nav-item">
                  <a class="nav-link text-light" href="/fale-conosco/">
                    Fale Conosco
                  </a>
              </li>
              <li class="nav-item" >
                  <a class="nav-link text-light" href="/ajuda/">
                      Ajuda
                  </a>
              </li>
              <li class="nav-item">
                  {% with quantidade_itens=carrinho|length%}
                    {%if carrinho|length > 0%}
                      
                      <a class="nav-link text-light" href="{% url "carrinho:detalhes_carrinho"%}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-fill" viewBox="0 0 16 16">
                          <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                        </svg>
                        {%if valorTotal %}
                          {{quantidade_itens}} produto{{quantidade_itens|pluralize}} - R$ {{valorTotal.get_total_geral}}
                        {%else%}
                          {{quantidade_itens}} produto{{quantidade_itens|pluralize}} - R$ {{carrinho.get_total_geral}}
                        {%endif%}
                      </a>
                    {%else%}
                      <a class="nav-link text-light" href="{% url "carrinho:detalhes_carrinho"%}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-fill" viewBox="0 0 16 16">
                          <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                        </svg> 0
                      </a>
                    {%endif%}
                  {%endwith%}
              </li>
          </ul>
      </div>
    </div>
  </nav>

templates/snippets/footer.html
<div class="navbar fixed-bottom bg-primary text-white">
    <p>Desenvolvido por Wesley melo</p>
</div>